services:
  - type: web
    name: floral-atelier
    env: node
    plan: free
    region: oregon
    buildCommand: |
          yarn install --frozen-lockfile
    yarn build
    startCommand: yarn start
    envVars:
      - key: NODE_VERSION
        value: "18"
