services:
  - type: web
    name: floral-atelier
    env: node
    plan: free
    region: oregon
    buildCommand: |
      pnpm install
      pnpm build
    startCommand: pnpm start
    envVars:
      - key: NODE_VERSION
        value: "18"
